<a href="https://colab.research.google.com/github/Nancy2615/nancy/blob/main/Multiplicacion_de_las_matrices%2C_asociativa%2C_distributiva%2C_no_es_conmutativa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

In [13]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])
C = np.array([[3,1],[4,2]])

In [5]:
#Asociativa
ABC = A.dot(B.dot(C))
print(ABC)

[[ 359  157]
 [ 797  349]
 [1235  541]
 [1673  733]]


In [7]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 359  157]
 [ 797  349]
 [1235  541]
 [1673  733]]


In [14]:
#Distrubutiva
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

ValueError: ignored

In [9]:
print(D)
print(E)

NameError: ignored

In [15]:
print(D==E)

NameError: ignored

In [16]:
F=B.dot(C)

In [17]:
G=C.dot(B)

ValueError: ignored

In [18]:
print(F==G)

NameError: ignored

In [19]:
print(F)

[[18  8]
 [43 19]
 [85 37]]


In [20]:
print(G)

NameError: ignored

In [21]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [23]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [24]:
print(v1_tv2)

[[41]]


In [25]:
print(v2_tv1)

[[41]]
