<a href="https://colab.research.google.com/github/Nancy2615/nancy/blob/main/Producto_entre_una_matriz_y_un_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = matriz * vector

ValueError: ignored

In [4]:
B = matriz.dot(vector)


ValueError: ignored

In [5]:
print(A)

NameError: ignored

In [6]:
print(B)

NameError: ignored

In [7]:
import numpy as np

vector = np.array([2,3,5])
print("\nVector: ",vector)

matriz = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
print("\nMatriz: ",matriz)

A = matriz.dot(vector)
print("\nmatrizXvector: ",A)

B = vector.dot(matriz)
print("\nvectorXmatriz: ",B)


Vector:  [2 3 5]

Matriz:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

matrizXvector:  [23 53 83]

vectorXmatriz:  [49 59 69]


In [8]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[23 53 83]
[23 53 83]
