<a href="https://colab.research.google.com/github/Nancy2615/nancy/blob/main/Transposicion_de_un_producto_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [3]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
print(B)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [5]:
AB_t = A.dot(B).T

In [6]:
B_tA_t = B.T.dot(A.T)

In [7]:
print(AB_t == B_tA_t)

[[ True  True  True  True]
 [ True  True  True  True]]


In [8]:
print(AB_t)

[[ 45  99 153 207]
 [ 56 125 194 263]]
